### ISSUE TITLE
Practica AR de Reconocimiento con GPS

### ISSUE THREAD

**Issue by AxayacatlS** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-axayacatl#2]
[Practica de reconocimiento.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-equipo-axayacatl/files/6674121/Practica.de.reconocimiento.pdf)

**Comment by Francisco536** [comment]
Calificación: 19.4 
Excelente trabajo compañeros

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
